### ISSUE TITLE
Validate User-Data and Campsite-Data

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#15]
## Value statement - a requirement, not a solution
As a **(role)** 
I need **(an action)** 
so that **(a benefit)** 
## Acceptance criteria
- [x] email check
- [x] good password check
## Tasks
- [x] make password hashed
- [x] put token and user id authenticator to all points
## Size
small
