### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#16]
## Value statement - a requirement, not a solution
As a user 
I need to get access denied 
so that I can not see datas I don't have to see
## Acceptance criteria
- [x] no access without userID and token
## Tasks
- [x] put authenticaton to all accesspoints
- [x] delete old token
## Size
small
