### ISSUE TITLE
User on landing Pange

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#2]
## Login or Register
As a  user
I enter the home page
so that I can see a Logo, a short description and two buttons 'Sign In' and 'Log In'
## Description (Text, Scribble, Wireframe, Design)
![Home](https://user-images.githubusercontent.com/26790622/99852031-71ccfd80-2b80-11eb-9814-b075106e7df0.png)

## Acceptance criteria
- [x] Find two clickable Buttons
- [x] Find a nice Logo and striking description

## Tasks
- [x] write a wireframe
- [x] make a logo
- [x] install react app
- [x] write a home component
- [x] write a styleguidist for buttons

## Size
medium
