### ISSUE TITLE
Finishing

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#33]
## Value statement - a requirement, not a solution
Last things to Do
## Acceptance criteria
- [x] ReadMe FrontEnd & BackEnd
- [ ] Type Hints Entity groß?
- [x] useUser für Login und Registration

## Tasks
- [x] (todos for the team)
## Size
(small, medium, large)
