### ISSUE TITLE
Campsite Filter core

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#6]
##Campsite Filter Form
As a user 
I need form
so that I can filter my campsite requirements
## Description
![core_filter](https://user-images.githubusercontent.com/26790622/99941521-6f2ffb00-2d6e-11eb-8144-e2db8b831031.png)
## Acceptance criteria
React form with:
- [x] Attribute from BackEnd as checkpoints
- [x] Filter-Button
- [x] direct to results page
## Tasks
- [x] useState for filter
- [x] fetch to send filter to backend
- [x] business-logic to find and evaluate the results
- [x] send results back to frontend
- [x] put results to results page
 medium
