### ISSUE TITLE
Set up all tables in Database

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#8]
As a **(role)** 
I need **(an action)** 
so that **(a benefit)** 
## Acceptance criteria
- [x] Validation Post campsite: if postalCode and Street are the same -> dont put in database

## Tasks
- [x] all Entities
- [x] all Repositories
- [x] fill with some datas
- [x] change coordinates array from campsite in 
two attributes latitude and longitude
- [x] change input fields in react /new-campsite
## Size
medium
