### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/moskito#9]
## Value statement - a requirement, not a solution
As a backend admin
I need have an opportunity to store image
so that I can connect them with campsite
## Description (Text, Scribble, Wireframe, Design)
First backend entity and vinch installation made on branch uploads
## Acceptance criteria
- [ ] get imaged in backend and connect with entitys
- [ ] set upload
## Tasks
- [ ] vagrant databa update with branch upload
- [ ] find out how to get images in the backend storage
## Size
 medium
